"""schema update

Revision ID: ec22f737f5a3
Revises: 001
Create Date: 2026-01-26 17:05:18.877618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec22f737f5a3'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_base_batch_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_table('templates')
    op.add_column('process_data', sa.Column('co2_lower_bound', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('co2_upper_bound', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('sox_lower_bound', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('sox_upper_bound', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('nox_lower_bound', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('nox_upper_bound', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('prediction_confidence', sa.Float(), nullable=True))
    op.add_column('process_data', sa.Column('uncertainty_data', sa.JSON(), nullable=True))
    op.add_column('process_data', sa.Column('model_metadata', sa.JSON(), nullable=True))
    op.create_index('ix_process_data_created_at', 'process_data', ['created_at'], unique=False)
    op.create_index('ix_process_data_project_id', 'process_data', ['project_id'], unique=False)
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'iso_compliance_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'iso_compliance_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('projects', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_process_data_project_id', table_name='process_data')
    op.drop_index('ix_process_data_created_at', table_name='process_data')
    op.drop_column('process_data', 'model_metadata')
    op.drop_column('process_data', 'uncertainty_data')
    op.drop_column('process_data', 'prediction_confidence')
    op.drop_column('process_data', 'nox_upper_bound')
    op.drop_column('process_data', 'nox_lower_bound')
    op.drop_column('process_data', 'sox_upper_bound')
    op.drop_column('process_data', 'sox_lower_bound')
    op.drop_column('process_data', 'co2_upper_bound')
    op.drop_column('process_data', 'co2_lower_bound')
    op.create_table('templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metal_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('default_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('templates_pkey'))
    )
    op.create_table('scenarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('base_batch_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('original_co2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scenario_co2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reduction_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scenarios_pkey'))
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_index(op.f('ix_scenarios_base_batch_id'), 'scenarios', ['base_batch_id'], unique=False)
    # ### end Alembic commands ###
